# Generated by Django 4.2 on 2023-05-02 12:26

import apps.tasties.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasty',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to=apps.tasties.models.generate_image_path_for_tasty)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('recepie', models.TextField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tasties', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by_user_id', related_query_name='%(app_label)s_%(class)s_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_by_user_id', related_query_name='%(app_label)s_%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
            ],
            options={
                'verbose_name': 'Tasty',
                'verbose_name_plural': 'Tasties',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
                ('volume', models.PositiveSmallIntegerField()),
                ('unit', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by_user_id', related_query_name='%(app_label)s_%(class)s_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_by_user_id', related_query_name='%(app_label)s_%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
                ('tasty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='tasties.tasty')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.AddIndex(
            model_name='tasty',
            index=models.Index(fields=['title'], name='tasties_tas_title_1cc8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name'], name='tasties_ing_name_f4c417_idx'),
        ),
    ]
