# Generated by Django 4.2 on 2023-05-02 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0003_foodcategory_and_more'),
        ('tasties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasty',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasties', to=settings.AUTH_USER_MODEL),
        ),
    ]
