# Generated by Django 4.2 on 2023-05-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_foodcategory_and_more'),
        ('tasties', '0002_tasty_category_alter_tasty_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasty',
            name='category',
            field=models.ForeignKey(default='3af3a44c-e8ea-11ed-a0f8-784f4383082e', on_delete=django.db.models.deletion.PROTECT, related_name='tasties', to='general.foodcategory'),
            preserve_default=False,
        ),
    ]
