# Generated by Django 4.2 on 2023-05-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasties', '0003_tasty_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pint'), (1, 'Table Spoon'), (2, 'Ounce'), (3, 'Cup'), (4, 'Numbers')], default=4),
        ),
    ]
