# Generated by Django 4.2 on 2023-05-03 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasties', '0004_alter_ingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasty',
            name='likes',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
                ('rating', models.PositiveSmallIntegerField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by_user_id', related_query_name='%(app_label)s_%(class)s_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_by_user_id', related_query_name='%(app_label)s_%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
                ('tasty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='tasties.tasty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_time',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by_user_id', related_query_name='%(app_label)s_%(class)s_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_by_user_id', related_query_name='%(app_label)s_%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
                ('tasty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='tasties.tasty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_time',),
                'abstract': False,
            },
        ),
    ]
