# Generated by Django 4.2 on 2023-05-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasties', '0006_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasty',
            old_name='recepie',
            new_name='recipe',
        ),
    ]
