apiVersion: v1
kind: Secret

metadata:
  name: app-secrets
#  namespace: database

type: Opaque

data:
  secret_key: base64encode(django secret key)
  postgres_db: base64encode(database name)
  postgres_user: base64encode
  postgres_password: base64encode
  db_host: base64encode(based on postgres pod or external db host)
  db_port: base64encode(based on postgres pod or external db host)
  listen_port: base64encode(nginx listen port)
  app_host: base64encode(django app host for nginx proxy mapping)
  app_port: base64encode(uwsgi worker port)
  redis_port: base64encode
  redis_password: base64encode
  celery_broker_url: base64encode
  celery_result_backend: base64encode
  admin_url: base64encode(custom admin url in production mode | debug=0)
  access_token_lifetime: base64encode(hours)
