# Generated by Django 4.2 on 2023-05-19 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
                ('reference', models.CharField(max_length=12, unique=True)),
                ('delivery', models.DateTimeField()),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Registered'), (1, 'Rejected'), (2, 'Canceled'), (3, 'Accepted')], default=0)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
