# Generated by Django 4.2 on 2023-05-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address_address_user_addres_title_6c7574_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
